# Generated by Django 3.2.5 on 2022-02-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0002_alter_student_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='photo',
            new_name='file',
        ),
    ]
